CREATE USER ADMIN IDENTIFIED BY ADMIN123
DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp 
QUOTA 20M ON users 
ACCOUNT UNLOCK;
/

GRANT ALL PRIVILEGES TO ADMIN;

CREATE USER STUDENT IDENTIFIED BY STUDENT123
DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp 
QUOTA 20M ON users 
ACCOUNT UNLOCK;
/

CREATE ROLE USER_ROLE;

GRANT CONNECT TO USER_ROLE;

GRANT SELECT ON ADMIN.assignment TO USER_ROLE;
GRANT SELECT ON ADMIN.assignment_students TO USER_ROLE;

GRANT USER_ROLE TO STUDENT;
GRANT USER_ROLE TO LECTURER;

GRANT INSERT,DELETE,UPDATE ON ADMIN.assignment TO LECTURER;
GRANT DELETE,UPDATE ON ADMIN.assignment_students TO LECTURER;
GRANT CREATE PROCEDURE TO LECTURER;


GRANT UPDATE (submit_file, status, submissionDate) ON ADMIN.assignment_students TO STUDENT;
GRANT EXECUTE ON ADMIN.submit_assignment_student TO STUDENT;







